<a href="https://colab.research.google.com/github/RodrigoARivasG/etl-data-pipeline/blob/main/data/raw/notebooks/etl_tipos_seguro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/RodrigoARivasG/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv")
df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [9]:
df.columns

Index(['id_tipo_seguro', 'tipo', 'categoria', 'riesgo_base'], dtype='object')

Limpieza de datos

In [12]:
tipos_seguro = df.copy()

# Normalizar nombres de columnas
tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

# Limpiar espacios en columnas de texto
for col in tipos_seguro.select_dtypes(include="object").columns:
    tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

# Reemplazar vacíos por NA
tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)

# Reemplazar valores tipo texto que representen nulos
tipos_seguro = tipos_seguro.replace(['nan', 'None', '-'], pd.NA)

# Convertir id_tipo_seguro a numérico
tipos_seguro['id_tipo_seguro'] = pd.to_numeric(
    tipos_seguro['id_tipo_seguro'],
    errors='coerce'
)

# Estandarizar tipo
tipos_seguro['tipo'] = (
    tipos_seguro['tipo']
    .astype(str)
    .str.strip()
    .str.title()
)

# Estandarizar categoria
tipos_seguro['categoria'] = (
    tipos_seguro['categoria']
    .astype(str)
    .str.strip()
    .str.title()
)

# Limpiar riesgo_base y convertir a numérico
tipos_seguro['riesgo_base'] = (
    tipos_seguro['riesgo_base']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.strip()
)

tipos_seguro['riesgo_base'] = pd.to_numeric(
    tipos_seguro['riesgo_base'],
    errors='coerce'
)

# Eliminar duplicados
tipos_seguro = tipos_seguro.drop_duplicates()

tipos_seguro

    id_tipo_seguro        tipo    categoria  riesgo_base
0                1        Pyme     Familiar          NaN
1                2  Industrial  Empresarial         4.68
2                3  Industrial     Familiar         5.10
3                4  Industrial     Personal          NaN
4                5        Auto  Empresarial         9.07
5                6  Industrial  Empresarial         2.52
6                7       Salud     Personal         0.92
7                8   Educación  Empresarial         7.42
8                9  Accidentes         <Na>         5.68
9               10      Dental     Especial         2.70
10              11        Auto  Empresarial         4.33
11              12    Agrícola         <Na>          NaN

In [21]:
seguros['riesgo_base'] = seguros['riesgo_base'].replace('-', pd.NA)

seguros['riesgo_base'] = seguros['riesgo_base'].astype(str).str.replace(',', '.', regex=False)

seguros['riesgo_base'] = pd.to_numeric(seguros['riesgo_base'], errors='coerce')

Revisar nulos por columna

In [13]:
tipos_seguro.isna().sum()

id_tipo_seguro    0
tipo              0
categoria         0
riesgo_base       3
dtype: int64

Separar datos válidos y rechazados

In [14]:
validos = tipos_seguro[
    tipos_seguro['id_tipo_seguro'].notna() &
    tipos_seguro['tipo'].notna() &
    tipos_seguro['categoria'].notna()
].copy()

rechazados = tipos_seguro[
    tipos_seguro['id_tipo_seguro'].isna() |
    tipos_seguro['tipo'].isna() |
    tipos_seguro['categoria'].isna()
].copy()

Agregar motivo de rechazo

In [15]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_tipo_seguro']):
        motivos.append("id_tipo_seguro_vacio")

    if pd.isna(row['tipo']):
        motivos.append("tipo_vacio")

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacia")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

rechazados

Empty DataFrame
Columns: [id_tipo_seguro, tipo, categoria, riesgo_base, motivo_rechazo]
Index: []

Ver cuántos válidos y rechazados hay

In [16]:
print("Registros válidos:", len(validos))
print("Registros rechazados:", len(rechazados))

Registros válidos: 12
Registros rechazados: 0

Exportar archivos CSV

In [17]:
validos.to_csv("tipos_seguro_curated.csv", index=False)
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

Instalar librerías para PostgreSQL y Conectar a BD

In [18]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_rivas:ks9EQNpC43n64cYY21G6e2BUn85omaRa@dpg-d6qu610gjchc73en58b0-a.oregon-postgres.render.com/etl_seguros_h814"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 57.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar tablas a PostgreSQL

In [19]:
validos.to_sql(
    'tipos_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipos_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

0

Verificar datos cargados

In [22]:
pd.read_sql(
    "SELECT * FROM tipos_seguro_curated LIMIT 10",
    engine
)

   id_tipo_seguro        tipo    categoria  riesgo_base
0               1        Pyme     Familiar          NaN
1               2  Industrial  Empresarial         4.68
2               3  Industrial     Familiar         5.10
3               4  Industrial     Personal          NaN
4               5        Auto  Empresarial         9.07
5               6  Industrial  Empresarial         2.52
6               7       Salud     Personal         0.92
7               8   Educación  Empresarial         7.42
8               9  Accidentes         <Na>         5.68
9              10      Dental     Especial         2.70